### Health check
GET http://localhost:8080/api/health

### About check
GET http://localhost:8080/api/about

### GET all tickets
GET http://localhost:8080/api/tickets

### Get one existing ticket
GET http://localhost:8080/api/tickets/T002

### Get one missing ticket
GET http://localhost:8080/api/tickets/T999

### create new valid ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "VPN connection not working",
  "description": "User cannot connect to company VPN from home.",
  "category": "Network",
  "priority": "MEDIUM",
  "createdBy": "siti@example.com"
}

###create an invalid ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "",
  "description": "",
  "category": "",
  "priority": "",
  "createdBy": ""
}

###all endpoints are working fine.