### Health check
GET http://localhost:8080/api/health

### About check
GET http://localhost:8080/api/about

### GET all tickets
GET http://localhost:8080/api/tickets

### Get one existing ticket
GET http://localhost:8080/api/tickets/6a50650ad0e1026b90eb03bd

### Get one missing ticket
GET http://localhost:8080/api/tickets/000000000000000000000000

### create new valid ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "Cannot access email",
  "description": "User cannot login to company email account.",
  "category": "Email",
  "priority": "HIGH",
  "createdBy": "amir@example.com"
}

###create an invalid ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "",
  "description": "",
  "category": "",
  "priority": "",
  "createdBy": ""
}

###all endpoints are working fine.