### GET all tickets
GET http://localhost:8080/api/tickets

###query for status "OPEN"
GET http://localhost:8080/api/tickets?status=OPEN

###query for priority "HIGH"
GET http://localhost:8080/api/tickets?priority=HIGH

###query for category "Email"
GET http://localhost:8080/api/tickets?category=Email

###Get paged tickets
GET http://localhost:8080/api/tickets/paged?page=0&size=5

####Get paged tickets with sorting
GET http://localhost:8080/api/tickets/paged?page=0&size=5&sortBy=createdAt&direction=desc