### Health check
GET http://localhost:8080/api/health

### About check
GET http://localhost:8080/api/about

### GET all tickets
GET http://localhost:8080/api/tickets

### Get one existing ticket
GET http://localhost:8080/api/tickets/6a50650ad0e1026b90eb03bd

### Get one missing ticket
GET http://localhost:8080/api/tickets/000000000000000000000000

### create new valid ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "Cannot access email",
  "description": "User cannot login to company email account.",
  "category": "Email",
  "priority": "HIGH",
  "createdBy": "amir@example.com"
}

###create an invalid ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "",
  "description": "",
  "category": "",
  "priority": "",
  "createdBy": ""
}

###query for status "OPEN"
GET http://localhost:8080/api/tickets?status=OPEN

###query for priority "HIGH"
GET http://localhost:8080/api/tickets?priority=HIGH

###query for category "Email"
GET http://localhost:8080/api/tickets?category=Email

###all endpoints are working fine.

@baseUrl = http://localhost:8080

### 3. Register a normal user - should return token with role USER
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Normal User",
  "email": "user@example.com",
  "password": "User@12345"
}

### login as admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin@12345"
}

### Testing V1 Endpoints with and without token
### 1. Test V1 without token (Should reject with 401 Unauthorized)
GET http://localhost:8080/api/v1/tickets
Content-Type: application/json


### 2. Login as normal USER to get a token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "User@12345"
}

# {%
#     // Assuming your REST client can save variables. If not, copy the token manually.
#     client.global.set("auth_token", response.body.token);
# %}

@auth_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpc3MiOiJhc3NldC10cmFja2VyLWFwaSIsIm5hbWUiOiJOb3JtYWwgVXNlciIsImV4cCI6MTc4NDM2Mjg4NiwiaWF0IjoxNzg0MzU5Mjg2LCJ1c2VySWQiOiI2YTViMjBiZGFiNTQ4ZTM5MzBmZDYzYjcifQ.zYq0WCOa0LaHVwFcVoAy_5l-_Cre47IYjw5Vv5rQX-U
### 3. Test V1 WITH valid USER token (Should succeed with 200 OK)
GET http://localhost:8080/api/v1/tickets
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### 4. Test Old Route with valid token (Should still work for backwards compatibility!)
GET http://localhost:8080/api/tickets
Content-Type: application/json
Authorization: Bearer {{auth_token}}